remote_theme: daattali/beautiful-jekyll@6.0.1

title: Lorem Ipsum
author: Foo Bar Baz

# --- Footer social media links --- #

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: false

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: false

# --- Colours / background image --- #

# Personalize the colours in your website. Colour values can be any valid CSS colour

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"

# --- Misc --- #

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: false
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
